name: "Update XML feed"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  schedule:
    - cron:  '0 9 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.ASCS }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Python tools
      run: sudo apt-get update && sudo apt-get -y install python3 python3-venv

    - name: Get Python version
      run: python3 --version

    - name: List contents of the current folder
      run: ls

    - name: Create virtual environment
      run: cd src && python3 -m venv env

    - name: List contents of the current folder
      run: ls src

    - name: Process dependencies & update feed
      run: |
        source src/env/bin/activate
        pip install -r src/requirements.txt
        cd src
        python -m hwu

    - uses: actions/checkout@v2
      with:
        repository: 'dendeli-work/feeds'
        path: '_feeds'

    - name: Copy and paste the new feed
      run: |
        ls src
        echo '====='
        ls _feeds/hello-world
        cp src/feed.xml _feeds/hello-world/feed.xml

    - name: Commit & push
      run: |
        cd _feeds
        ls
        git status
        echo '====='
        git add .
        echo '====='
        git config --global user.name 'Den Delimarsky'
        git config --global user.email '1389609+dend@users.noreply.github.com'
        echo '====='
        git remote set-url --push origin https://dend:{{ secrets.FEEDS_PAT }}@github.com/dendeli-work/feeds.git
        git commit -m "Feed update."
        git push origin main
